# Generated by Django 3.1.3 on 2020-12-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('birthday', models.TextField(blank=True)),
                ('sex', models.TextField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('alignment', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('powers', models.TextField(blank=True)),
                ('image_main', models.ImageField(upload_to='portfolio/images/')),
                ('image_1', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('image_2', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('image_3', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('tech', models.TextField(blank=True)),
            ],
        ),
    ]
