# Generated by Django 3.1.3 on 2020-12-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='character',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='character',
            name='url',
        ),
    ]
