# Generated by Django 3.1.3 on 2020-12-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20201222_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='characters/images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='characters/images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='characters/images/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_main',
            field=models.ImageField(upload_to='characters/images/'),
        ),
    ]
