# Generated by Django 3.1.3 on 2020-12-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.IntegerField(blank=True)),
                ('saga', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('japan_air_date', models.TextField(blank=True)),
                ('usa_air_date', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='episodes/images/')),
            ],
        ),
    ]
